<link rel="stylesheet" type="text/css" href="{{asset('backend/bootstrap/css/bootstrap.min.css')}}">
<link rel="stylesheet" type="text/css" href="{{asset('backend/css/style.css')}}">
<link rel="stylesheet" type="text/css" href="{{asset('backend/css/kalife.css')}}">
<link rel="stylesheet" type="text/css" href="{{asset('backend/plugins/izi/iziModal.css')}}">
<link rel="stylesheet" type="text/css" href="{{asset('backend/plugins/izi/iziToast.css')}}">
<link rel="stylesheet" type="text/css" href="{{asset('backend/css/dropzone.min.css')}}">
<link rel="stylesheet" type="text/css" href="{{asset('backend/css/bootstrap-datetimepicker.min.css')}}">
<link href="{{asset("css/toastr.min.css")}}" rel="stylesheet" type="text/css"/>
<link rel="stylesheet"  href="{{asset('backend/plugins/DataTables/css/jquery.dataTables.min.css')}}" >